GO ?= go
BINARY ?= hytop
BUILD_DIR ?= build
DIST_DIR ?= dist
TARGET_OS ?= $(shell $(GO) env GOOS)
TARGET_ARCH ?= $(shell $(GO) env GOARCH)
TARGET_EXT = $(if $(filter windows,$(TARGET_OS)),.exe,)
TARGET_BINARY = $(BINARY)$(TARGET_EXT)
UPX_BINARY = $(BINARY)-upx$(TARGET_EXT)
UPX ?= upx
VERSION ?= dev
COMMIT ?= unknown
BUILD_DATE ?= unknown

DEBUG_FLAGS = -gcflags=all=-N\ -l
VERSION_PACKAGE = github.com/Hayao0819/hytop/internal/version
VERSION_FLAGS = -X $(VERSION_PACKAGE).Version=$(VERSION) -X $(VERSION_PACKAGE).Commit=$(COMMIT) -X $(VERSION_PACKAGE).Date=$(BUILD_DATE)
BUILD_FLAGS = -ldflags='$(VERSION_FLAGS)'
RELEASE_FLAGS = -trimpath -ldflags='-s -w $(VERSION_FLAGS)'

ARCH_GO = $(GO) run github.com/arch-go/arch-go/v2@v2.1.2
GOLANGCI_LINT = $(GO) run github.com/golangci/golangci-lint/v2/cmd/golangci-lint@v2.13.2
GOFUMPT = $(GO) run mvdan.cc/gofumpt@v0.11.0
LICHEN = $(GO) run github.com/uw-labs/lichen@v0.1.8-0.20260509120439-123c7db4d411
ACTIONLINT = $(GO) run github.com/rhysd/actionlint/cmd/actionlint@v1.7.12
GOVULNCHECK = $(GO) run golang.org/x/vuln/cmd/govulncheck@v1.8.0
LICENSE_TARGETS = linux/amd64 linux/arm64 linux/386 linux/riscv64 darwin/amd64 darwin/arm64 windows/amd64 windows/arm64
THIRD_PARTY_FILE = THIRD_PARTY_LICENSES
export CGO_ENABLED = 0

.PHONY: build debug release dist release-upx test race lint fmt-check tidy deps licenses licenses-check workflows vulnerabilities check clean

build:
	mkdir -p $(BUILD_DIR)
	$(GO) build $(BUILD_FLAGS) -o $(BUILD_DIR)/$(BINARY) .

debug:
	mkdir -p $(BUILD_DIR)
	$(GO) build $(DEBUG_FLAGS) $(BUILD_FLAGS) -o $(BUILD_DIR)/$(BINARY)-debug .

release:
	mkdir -p $(DIST_DIR)
	GOOS=$(TARGET_OS) GOARCH=$(TARGET_ARCH) $(GO) build $(RELEASE_FLAGS) -o $(DIST_DIR)/$(TARGET_BINARY) .

dist: release
	tar -czf $(DIST_DIR)/$(BINARY)-$(TARGET_OS)-$(TARGET_ARCH).tar.gz \
		-C $(DIST_DIR) $(TARGET_BINARY) -C $(CURDIR) LICENSE README.md $(THIRD_PARTY_FILE)

release-upx: release
	command -v $(UPX)
	cp $(DIST_DIR)/$(TARGET_BINARY) $(DIST_DIR)/$(UPX_BINARY)
	$(UPX) --best $(DIST_DIR)/$(UPX_BINARY)
	$(UPX) --test $(DIST_DIR)/$(UPX_BINARY)

test:
	$(GO) test ./...

race:
	CGO_ENABLED=1 $(GO) test -race ./...

lint:
	$(GO) vet ./...
	$(GOLANGCI_LINT) run
	$(MAKE) fmt-check

fmt-check:
	@files="$$( $(GOFUMPT) -l -e . )" || exit $$?; \
	if [ -n "$$files" ]; then \
		printf '%s\n' "$$files"; \
		exit 1; \
	fi

tidy:
	$(GO) mod tidy

deps:
	$(ARCH_GO) --color no

licenses:
	@command -v jq >/dev/null || { printf '%s\n' 'jq is required to generate third-party licenses' >&2; exit 1; }
	@set -eu; \
	work="$$(mktemp -d)"; \
	trap 'rm -rf "$$work"' 0 1 2 15; \
	binaries=""; \
	for target in $(LICENSE_TARGETS); do \
		os="$${target%/*}"; \
		arch="$${target#*/}"; \
		binary="$$work/$(BINARY)-$$os-$$arch"; \
		GOOS="$$os" GOARCH="$$arch" $(GO) build -trimpath -o "$$binary" .; \
		binaries="$$binaries $$binary"; \
	done; \
	$(LICHEN) --config=.lichen.yaml --json="$$work/licenses.json" --template='' $$binaries >/dev/null; \
	{ \
		printf '%s\n\n' 'Third-party licenses and notices' \
			'This file is generated by `make licenses` from the modules linked into release binaries.'; \
		goroot="$$( $(GO) env GOROOT )"; \
		goversion="$$( $(GO) env GOVERSION )"; \
		for document in LICENSE PATENTS; do \
			printf '================================================================================\nGo standard library (%s) — %s\n================================================================================\n' \
				"$$goversion" "$$document"; \
			cat "$$goroot/$$document"; \
			printf '\n'; \
		done; \
		jq -r '.Modules | sort_by(.Path, .Version)[] | "================================================================================\n\(.Path)@\(.Version)\n================================================================================\n" + ([.Licenses | unique_by(.Path)[] | .Content] | join("\n"))' "$$work/licenses.json"; \
	} > "$$work/output"; \
	jq -r '.Modules | sort_by(.Path, .Version)[] | [.Path, .Version, .Dir] | @tsv' "$$work/licenses.json" | \
	while IFS="$$(printf '\t')" read -r module version dir; do \
		for notice in "$$dir"/NOTICE* "$$dir"/notice*; do \
			[ -f "$$notice" ] || continue; \
			printf '\n================================================================================\n%s@%s — %s\n================================================================================\n' \
				"$$module" "$$version" "$$(basename "$$notice")" >> "$$work/output"; \
			cat "$$notice" >> "$$work/output"; \
			printf '\n' >> "$$work/output"; \
		done; \
	done; \
	awk '{ sub(/[[:space:]]+$$/, ""); lines[NR] = $$0 } END { last = NR; while (last > 0 && lines[last] == "") last--; for (i = 1; i <= last; i++) print lines[i] }' \
		"$$work/output" > "$$work/final"; \
	mv "$$work/final" $(THIRD_PARTY_FILE)

licenses-check:
	@set -eu; \
	before="$$(mktemp)"; \
	trap 'rm -f "$$before"' 0 1 2 15; \
	cp $(THIRD_PARTY_FILE) "$$before"; \
	$(MAKE) licenses; \
	cmp -s "$$before" $(THIRD_PARTY_FILE) || { \
		diff -u "$$before" $(THIRD_PARTY_FILE) || true; \
		exit 1; \
	}

workflows:
	$(ACTIONLINT)

vulnerabilities:
	$(GOVULNCHECK) ./...

check: lint build race deps licenses-check workflows vulnerabilities

clean:
	rm -f hytop coverage.out
	rm -rf build dist
