name: ci

on:
  push:
  pull_request:

env:
  CGO_ENABLED: "0"

permissions:
  contents: read

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          path: hytop
          persist-credentials: false

      - uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version-file: hytop/go.mod
          cache-dependency-path: hytop/go.sum

      - run: make check
        working-directory: hytop

  linux-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goarch: [amd64, arm64, "386", riscv64]
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          path: hytop
          persist-credentials: false

      - uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version-file: hytop/go.mod
          cache-dependency-path: hytop/go.sum

      - run: go build -trimpath -ldflags="-s -w" ./
        working-directory: hytop
        env:
          GOOS: linux
          GOARCH: ${{ matrix.goarch }}

      - name: Test Linux/386
        if: matrix.goarch == '386'
        run: go test ./...
        working-directory: hytop
        env:
          GOOS: linux
          GOARCH: "386"

  native-test:
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          path: hytop
          persist-credentials: false

      - uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version-file: hytop/go.mod
          cache-dependency-path: hytop/go.sum

      - run: go test ./...
        working-directory: hytop
